name: iproute2-snap
version: '6.6.0'
license: GPL-2.0-only
summary: This is a set of utilities for Linux networking.
description: Iproute2 is a collection of utilities for controlling TCP / IP networking and traffic control in Linux.
base: core22 
grade: stable
confinement: strict

parts:
  iproute2:
    plugin: make
    source: https://git.kernel.org/pub/scm/network/iproute2/iproute2
    source-type: git
    source-tag: v6.6.0
    build-packages: 
      - libdb5.3-dev 
      - libmnl-dev
      - build-essential
      - bison
      - flex
      - pkg-config
apps:
  ip:
    command: sbin/ip
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  dcb:
    command: sbin/dcb
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  devlink:
    command: sbin/devlink
    plugs: 
       - network
       - network-bind
       - network-control
       - network-observe
  tc:
    command: sbin/tc
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  arpd:
    command: sbin/arpd
    plugs: 
       - network
       - network-bind
       - network-control
       - network-observe
  ctstat:
    command: sbin/ctstat
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  nstat:
    command: sbin/nstat
    plugs: 
       - network
       - network-bind
       - network-control
       - network-observe
  routel:
    command: sbin/routel
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  rtmon:
    command: sbin/rtmon
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  rtstat:
    command: sbin/rtstat
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  rdma:
    command: sbin/rdma
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  bridge:
    command: sbin/bridge
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  genl:
    command: sbin/genl
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  lnstat:
    command: sbin/lnstat
    plugs: 
       - network
       - network-bind
       - network-control
       - network-observe
  rtacct:
    command: sbin/rtacct
    plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  ss:
    command: sbin/ss
    plugs: 
       - network
       - network-bind
       - network-control
       - network-observe
  ifstat:
     command: sbin/ifstat
     plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  tipc:
     command: sbin/tipc
     plugs:
       - network
       - network-bind
       - network-control
       - network-observe
  vdpa:
     command: sbin/vdpa
     plugs:
       - network
       - network-bind
       - network-control
       - network-observe
